### ISSUE TITLE
Debug - Schedulejob

### ISSUE THREAD

**Issue by rajeshvartak** [OfficeDev/PnP-Partner-Pack#167] opened 2016-10-13 20:07 UTC
Hi, 
is there anyway i can debug the ScheduleJob ?

I tried to create site collection using online template of "Curriculam Vitae Database" and that end with error 
"[10/13/2016 19:01:25 > 3ac469: INFO] Exception occurred: The field was found invalid:  {termsetid:Company:Potential Roles}"

Then i tried to create site collection using "Empty Site Template" and it ended with error, please refer the log below.  

10/13/2016 15:14:44 > 3ac469: SYS INFO] Status changed to Initializing
[10/13/2016 15:14:44 > 3ac469: SYS INFO] Job directory change detected: Job file 'Microsoft.Office.Client.Policy.dll' timestamp differs between source and working directories.
[10/13/2016 15:14:45 > 3ac469: SYS INFO] Run script 'OfficeDevPnP.PartnerPack.ScheduledJob.exe' with script host - 'WindowsScriptHost'
[10/13/2016 15:14:45 > 3ac469: SYS INFO] Status changed to Running
[10/13/2016 15:14:46 > 3ac469: INFO] Starting job
[10/13/2016 15:14:47 > 3ac469: INFO] Processing jobs in Site: PnP Partner Pack 2 - Infrastructural Site
[10/13/2016 15:14:50 > 3ac469: INFO] Processing job: f27d00b3-db28-4ef2-a333-7bf9b57157c0 - Owner: [USER]@[TENANTNAME].onmicrosoft.com - Title: Provisioning of Site Collection "/sites/pnp1" with Template "https://[TENANTNAME].sharepoint.com/sites/PnP-Partner-Pack-Infrastructure2/PnPProvisioningTemplates/PnP-Empty-Site.xml" by [USER]@[TENANTNAME].onmicrosoft.com
[10/13/2016 15:14:52 > 3ac469: INFO] Creating Site Collection "/sites/pnp1".
[10/13/2016 15:19:49 > 3ac469: INFO] Site "https://[TENANTNAME].sharepoint.com/sites/pnp1" created.
[10/13/2016 15:19:59 > 3ac469: INFO] Enabled PnP Partner Pack Overrides on site "https://[TENANTNAME].sharepoint.com/sites/pnp1".
[10/13/2016 15:20:04 > 3ac469: INFO] Enabled Responsive Design Template to site "https://[TENANTNAME].sharepoint.com/sites/pnp1".
[10/13/2016 15:20:04 > 3ac469: INFO] Applying Provisioning Template "https://[TENANTNAME].sharepoint.com/sites/PnP-Partner-Pack-Infrastructure2/PnPProvisioningTemplates/PnP-Empty-Site.xml" to site.
[10/13/2016 15:20:06 > 3ac469: INFO] Exception occurred: Object reference not set to an instance of an object.
[10/13/2016 15:20:06 > 3ac469: INFO] Stack Trace:
[10/13/2016 15:20:06 > 3ac469: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job) in C:\DEV\PnP-Partner-Pack-master\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\SiteCollectionProvisioningJobHandler.cs:line 180
[10/13/2016 15:20:06 > 3ac469: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job) in C:\DEV\PnP-Partner-Pack-master\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\SiteCollectionProvisioningJobHandler.cs:line 28
[10/13/2016 15:20:06 > 3ac469: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job) in C:\DEV\PnP-Partner-Pack-master\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\ProvisioningJobHandler.cs:line 46
[10/13/2016 15:20:06 > 3ac469: INFO] 
[10/13/2016 15:20:06 > 3ac469: INFO] Ending job

**Comment by erwinvanhunen** [comment] 2016-10-13 21:11
It was an issue with the template actually. We fixed it, so please try again to create the sitecollection based upon that webtemplate.

**Comment by rajeshvartak** [comment] 2016-10-14 13:47
Thanks Erwin for template update it worked 👍 

Can you suggest what i can do to debug the Azure Webjob  "ScheduledJob" ?

**Comment by camiloborges** [comment] 2016-10-21 02:42
Hello. I am able to debug any of the jobs locally by making sure the self signed certificate is imported in my personal certificate store. You need to import the .PFX one.

**Comment by rajeshvartak** [comment] 2016-10-21 14:51
Hi Camilo,

I can also debug the jobs locally, I am talking about debugging the scheduled job running on Azure. I have fixed the issue by adding extra logging etc. but i am still curious if any one can debug the schedule job running on Azure from Visual Studio by attaching debugger.

Thanks,
Rajesh

**Comment by nikhilsarvaiye** [comment] 2016-10-26 10:09
Hi team,

the issue is at line 180 in SiteCollectionProvisioningJobHandler.cs as there is no null check
                       // Fixup Title and Description
                        template.WebSettings.Title = job.SiteTitle;
                        template.WebSettings.Description = job.Description;
I have updated the code and also refracted some code as there are so many places where context and urls are getting queries to SP

**Comment by VesaJuvonen** [comment] 2016-10-27 15:34
Good catch Nikhil we would also appreciate PR towards this repo, so that we can get that processed. On the webjob debugging in general, following blog post has the details - https://blogs.msdn.microsoft.com/webdev/2014/11/12/new-developer-and-debugging-features-for-azure-webjobs-in-visual-studio/. 

Since issue seems to be now resolved and questions answered, will close this one. If there's any other findings or pending things, feel free to re-open. thx for your contributions.

**Closed by VesaJuvonen** 2016-10-27 15:34 UTC
